version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - COGNITO_REGION=sa-east-1
      - COGNITO_APP_CLIENT_ID=seu-client-id
      - COGNITO_USER_POOL_ID=seu-user-pool-id
      - JWT_SECRET=uma-senha-secreta

   db:
    image: postgres:13 
    container_name: bff-postgres 
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bff
    volumes:
      - db_data:/var/lib/postgresql/data

env_file:
  - .env

volumes:
  db_data:
